build_settings:
  clone_depth: 1
  mysql:
    host: "localhost"
    user: "phpci-tmcms-empt"
    pass: "phpci-tmcms-empty"

setup:
  composer:
    action: "install"

test:
  php_unit:
    config:
      - "vendor/devp-eu/tmcms-tests/src/phpunit.xml"
    directory:
      - "vendor/devp-eu/tmcms-tests/src/"
    args: "--bootstrap 'vendor/devp-eu/tmcms-tests/src/phpunit_bootstrap.php' --configuration 'vendor/devp-eu/tmcms-tests/src/phpunit.xml'"
    coverage: "coverage"
  shell:
    - "./vendor/devp-eu/tmcms-tests/src/run_project_tests.sh"
  php_parallel_lint:
    directory: "project"
  php_cpd:
    standard: "PSR2"
    path: "project"

failure:
  email:
    committer: true
    default_mailto_address: support@devp.eu